# Generates the CamLink app icon artifacts shared with the Android launcher
# icons (same camera-glyph design, see temp/gen_icons.ps1 for the Android side):
#   pc/res/camlink.ico      multi-size .ico embedded in the Windows executable
#   pc/src/icon_data.h      32x32 RGBA pixel array for SDL_SetWindowIcon
# Run: pwsh -File pc/tools/gen_icon.ps1
$ErrorActionPreference = "Stop"
Add-Type -AssemblyName System.Drawing

$pcDir = Split-Path -Parent $PSScriptRoot
$resDir = Join-Path $pcDir "res"
$srcDir = Join-Path $pcDir "src"
New-Item -ItemType Directory -Force -Path $resDir | Out-Null

$bgColor = [System.Drawing.Color]::FromArgb(255, 0x1A, 0x1A, 0x2E)
$fgColor = [System.Drawing.Color]::White

function New-RoundedPath([float]$x, [float]$y, [float]$w, [float]$h, [float]$r) {
    $p = New-Object System.Drawing.Drawing2D.GraphicsPath
    $p.AddArc($x, $y, $r * 2, $r * 2, 180, 90)
    $p.AddArc($x + $w - $r * 2, $y, $r * 2, $r * 2, 270, 90)
    $p.AddArc($x + $w - $r * 2, $y + $h - $r * 2, $r * 2, $r * 2, 0, 90)
    $p.AddArc($x, $y + $h - $r * 2, $r * 2, $r * 2, 90, 90)
    $p.CloseFigure()
    return $p
}

function Render-Icon([int]$size) {
    $k = $size / 108.0
    $bmp = [System.Drawing.Bitmap]::new($size, $size)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = "AntiAlias"

    $bg = New-Object System.Drawing.SolidBrush $bgColor
    $fg = New-Object System.Drawing.SolidBrush $fgColor

    $bgPath = New-RoundedPath 0 0 $size $size ([Math]::Max(1, 18 * $k))
    $g.FillPath($bg, $bgPath)

    # camera body: design-space rect (22,38)-(86,70), radius 6
    $body = New-RoundedPath (22 * $k) (38 * $k) (64 * $k) (32 * $k) ([Math]::Max(1, 6 * $k))
    $g.FillPath($fg, $body)
    # top bump: (46,32)-(62,38)
    $g.FillRectangle($fg, 46 * $k, 32 * $k, 16 * $k, 6 * $k)
    # lens hole: center (54,54) r=8
    $g.FillEllipse($bg, (54 - 8) * $k, (54 - 8) * $k, 16 * $k, 16 * $k)
    # flash hole: center (76,44) r=3
    $g.FillEllipse($bg, (76 - 3) * $k, (44 - 3) * $k, 6 * $k, 6 * $k)

    $bgPath.Dispose(); $body.Dispose()
    $bg.Dispose(); $fg.Dispose()
    $g.Dispose()
    return $bmp
}

# --- .ico (PNG-compressed entries, 16..256 px) ---------------------------
$icoSizes = @(16, 24, 32, 48, 64, 256)
$pngBlobs = @()
foreach ($s in $icoSizes) {
    $bmp = Render-Icon $s
    $ms = New-Object System.IO.MemoryStream
    $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
    $pngBlobs += , $ms.ToArray()
    $ms.Dispose(); $bmp.Dispose()
}

$out = New-Object System.IO.MemoryStream
$bw = New-Object System.IO.BinaryWriter($out)
$bw.Write([uint16]0)                       # reserved
$bw.Write([uint16]1)                       # type: icon
$bw.Write([uint16]$icoSizes.Count)
$offset = 6 + 16 * $icoSizes.Count
for ($i = 0; $i -lt $icoSizes.Count; $i++) {
    $s = $icoSizes[$i]
    $dim = if ($s -ge 256) { 0 } else { $s }
    $bw.Write([byte]$dim)                  # width
    $bw.Write([byte]$dim)                  # height
    $bw.Write([byte]0)                     # colors in palette
    $bw.Write([byte]0)                     # reserved
    $bw.Write([uint16]1)                   # color planes
    $bw.Write([uint16]32)                  # bits per pixel
    $bw.Write([uint32]$pngBlobs[$i].Length)
    $bw.Write([uint32]$offset)
    $offset += $pngBlobs[$i].Length
}
foreach ($blob in $pngBlobs) { $bw.Write($blob) }
$bw.Flush()
$icoPath = Join-Path $resDir "camlink.ico"
[IO.File]::WriteAllBytes($icoPath, $out.ToArray())
$bw.Dispose(); $out.Dispose()
Write-Host "wrote $icoPath ($((Get-Item $icoPath).Length) bytes)"

# --- RGBA header for SDL_SetWindowIcon -----------------------------------
$iconSize = 32
$bmp = Render-Icon $iconSize
$bytes = New-Object System.Collections.Generic.List[byte]
for ($y = 0; $y -lt $iconSize; $y++) {
    for ($x = 0; $x -lt $iconSize; $x++) {
        $c = $bmp.GetPixel($x, $y)
        $bytes.Add($c.R); $bytes.Add($c.G); $bytes.Add($c.B); $bytes.Add($c.A)
    }
}
$bmp.Dispose()

$hex = for ($i = 0; $i -lt $bytes.Count; $i += 16) {
    $chunk = ($bytes[$i..([Math]::Min($i + 15, $bytes.Count - 1))] |
        ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
    "    $chunk,"
}
$header = @"
#pragma once

// Generated by pc/tools/gen_icon.ps1 - do not edit by hand.
// 32x32 RGBA pixels of the CamLink camera glyph (see the script for design).
#define CAMLINK_ICON_SIZE $iconSize
static const unsigned char kCamLinkIconRgba[CAMLINK_ICON_SIZE * CAMLINK_ICON_SIZE * 4] = {
$($hex -join "`n")
};
"@
$headerPath = Join-Path $srcDir "icon_data.h"
Set-Content -Path $headerPath -Value $header -Encoding Ascii
Write-Host "wrote $headerPath"
